export enum NotificationType {
  BLOG_SUBMITTED_FOR_REVIEW = 'BLOG_SUBMITTED_FOR_REVIEW',
  BLOG_REVIEWED = 'BLOG_REVIEWED',
  BLOG_REJECTED = 'BLOG_REJECTED',
  BLOG_APPROVED = 'BLOG_APPROVED',
  BLOG_PUBLISHED = 'BLOG_PUBLISHED',
  COMMENT_POSTED = 'COMMENT_POSTED',
  COMMENT_REPLY = 'COMMENT_REPLY',
}
